services:
  pi-container:
    command: pi
    image: docker.io/tarunsrisai/pi-container:latest
    volumes:
      - ${MODELS_JSON}:/root/.pi/agent/models.json:ro
      - ${PWD}:/app
    working_dir: /app
    tty: false
